---
kind: pipeline
type: docker
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: rancher/hardened-build-base:v1.20.4b11
  commands:
  - make DRONE_TAG=${DRONE_TAG} image-build-operator
  - make DRONE_TAG=${DRONE_TAG} image-build-network-config-daemon
  - make DRONE_TAG=${DRONE_TAG} image-build-sriov-network-webhook
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: publish
  image: rancher/hardened-build-base:v1.20.4b11
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make DRONE_TAG=${DRONE_TAG} image-push-operator image-manifest-operator
  - make DRONE_TAG=${DRONE_TAG} image-push-network-config-daemon image-manifest-network-config-daemon
  - make DRONE_TAG=${DRONE_TAG} image-push-sriov-network-webhook image-manifest-sriov-network-webhook
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag

- name: scan
  image: rancher/hardened-build-base:v1.20.4b11
  commands:
  - make DRONE_TAG=${DRONE_TAG} image-scan-operator
  - make DRONE_TAG=${DRONE_TAG} image-scan-network-config-daemon
  - make DRONE_TAG=${DRONE_TAG} image-scan-sriov-network-webhook
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  pull: always
  image: rancher/hardened-build-base:v1.20.4b11
  commands:
  - make DRONE_TAG=${DRONE_TAG} image-build-operator
  - make DRONE_TAG=${DRONE_TAG} image-build-network-config-daemon
  - make DRONE_TAG=${DRONE_TAG} image-build-sriov-network-webhook
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: publish
  image: rancher/hardened-build-base:v1.20.4b11
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make DRONE_TAG=${DRONE_TAG} image-push-operator image-manifest-operator
  - make DRONE_TAG=${DRONE_TAG} image-push-network-config-daemon image-manifest-network-config-daemon
  - make DRONE_TAG=${DRONE_TAG} image-push-sriov-network-webhook image-manifest-sriov-network-webhook
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag

- name: scan
  image: rancher/hardened-build-base:v1.20.4b11
  commands:
  - make DRONE_TAG=${DRONE_TAG} image-scan-operator
  - make DRONE_TAG=${DRONE_TAG} image-scan-network-config-daemon
  - make DRONE_TAG=${DRONE_TAG} image-scan-sriov-network-webhook
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
...
